fix: [N-04] Minor typographical errors
across-protocol/across-token pull request #51
Opened 2023-01-02 23:45 UTC by pxrl

Based on feedback from OZ.

2023-01-03 01:54 UTC, nicholaspai commented on contracts/AcceleratingDistributor.sol
> +        // Note: these will revert if underflow so you can't unstake more than your cumulativeBalance.
```suggestion
        // Note: these will revert if underflow occurs so you can't unstake more than your cumulativeBalance.
```

2023-01-03 01:55 UTC, nicholaspai requested changes
One missing nit!

2023-01-04 01:33 UTC, pxrl commented on contracts/AcceleratingDistributor.sol
> +        // Note: these will revert if underflow so you can't unstake more than your cumulativeBalance.
Addressed here: https://github.com/across-protocol/across-token/pull/51/commits/948f373af0ee1744e029ddc6ca88f923a89e1074

2023-01-04 14:52 UTC, nicholaspai approved these changes

2023-01-04 21:34 UTC, merged